export const defaultChecklistItems = [
  // Avant le départ
  { section: 'Avant le départ', title: 'Visa utilisateur A', concerns: 'user_a', plannedCost: 635, currency: 'AUD', status: 'todo' },
  { section: 'Avant le départ', title: 'Visa utilisateur B', concerns: 'user_b', plannedCost: 635, currency: 'AUD', status: 'todo' },
  { section: 'Avant le départ', title: 'Billets d’avion', concerns: 'common', status: 'todo' },
  { section: 'Avant le départ', title: 'Assurance voyage / santé', concerns: 'common', status: 'todo' },
  { section: 'Avant le départ', title: 'Passeports valides', concerns: 'common', status: 'todo' },
  { section: 'Avant le départ', title: 'Permis international', concerns: 'common', status: 'todo' },
  { section: 'Avant le départ', title: 'Compte bancaire australien', concerns: 'common', status: 'todo' },
  { section: 'Avant le départ', title: 'Carte bancaire sans frais', concerns: 'common', status: 'todo' },
  { section: 'Avant le départ', title: 'Résiliation / pause abonnements en France', concerns: 'common', status: 'todo' },
  { section: 'Avant le départ', title: 'Téléphone / forfait international', concerns: 'common', status: 'todo' },
  { section: 'Avant le départ', title: 'CV australien', concerns: 'common', status: 'todo' },
  { section: 'Avant le départ', title: 'Logement temporaire', concerns: 'common', status: 'todo' },
  { section: 'Avant le départ', title: 'Scan des documents importants', concerns: 'common', status: 'todo' },
  { section: 'Avant le départ', title: 'Argent de sécurité', concerns: 'common', status: 'todo' },
  { section: 'Avant le départ', title: 'Ordonnances / documents médicaux', concerns: 'common', status: 'todo' },
  
  // Après l'arrivée
  { section: 'Après l’arrivée', title: 'Acheter une carte SIM australienne', concerns: 'common', status: 'todo' },
  { section: 'Après l’arrivée', title: 'Activer le compte bancaire australien', concerns: 'common', status: 'todo' },
  { section: 'Après l’arrivée', title: 'Demander le TFN', concerns: 'common', status: 'todo' },
  { section: 'Après l’arrivée', title: 'Créer ou récupérer la Superannuation', concerns: 'common', status: 'todo' },
  { section: 'Après l’arrivée', title: 'Acheter une carte de transport', concerns: 'common', status: 'todo' },
  { section: 'Après l’arrivée', title: 'Trouver un logement long terme', concerns: 'common', status: 'todo' },
  { section: 'Après l’arrivée', title: 'Mettre à jour le CV avec adresse australienne', concerns: 'common', status: 'todo' },
  { section: 'Après l’arrivée', title: 'Commencer la recherche de job', concerns: 'common', status: 'todo' },
  { section: 'Après l’arrivée', title: 'Imprimer les documents importants', concerns: 'common', status: 'todo' },
  { section: 'Après l’arrivée', title: 'Acheter les essentiels pour le logement', concerns: 'common', status: 'todo' },

  // Valise
  { section: 'Valise', title: 'Passeport', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Visa imprimé / sauvegardé', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Billets d’avion', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Assurance', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Permis français', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Permis international', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Adaptateur Australie', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Chargeurs', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Batterie externe', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Médicaments', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Trousse de toilette', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Vêtements été', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Vêtements pluie', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Vêtements travail', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Chaussures confortables', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Maillot de bain', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Lunettes de soleil', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Sac cabine', concerns: 'common', status: 'todo' },
  { section: 'Valise', title: 'Sac principal', concerns: 'common', status: 'todo' },

  // Documents
  { section: 'Documents importants', title: 'Passeport utilisateur A', concerns: 'user_a', status: 'todo' },
  { section: 'Documents importants', title: 'Passeport utilisateur B', concerns: 'user_b', status: 'todo' },
  { section: 'Documents importants', title: 'Visa utilisateur A', concerns: 'user_a', status: 'todo' },
  { section: 'Documents importants', title: 'Visa utilisateur B', concerns: 'user_b', status: 'todo' },
  { section: 'Documents importants', title: 'Assurance', concerns: 'common', status: 'todo' },
  { section: 'Documents importants', title: 'Billets d’avion', concerns: 'common', status: 'todo' },
  { section: 'Documents importants', title: 'Permis international', concerns: 'common', status: 'todo' },
  { section: 'Documents importants', title: 'CV australien', concerns: 'common', status: 'todo' },
  { section: 'Documents importants', title: 'Ordonnances médicales', concerns: 'common', status: 'todo' },
  { section: 'Documents importants', title: 'Documents bancaires', concerns: 'common', status: 'todo' },
  { section: 'Documents importants', title: 'Contacts d’urgence', concerns: 'common', status: 'todo' }
]
